# Generated by Django 4.2.11 on 2024-04-12 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='owner',
        ),
    ]
