# Generated by Django 4.2.11 on 2024-04-16 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio_management', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='owners',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
