# Generated by Django 4.1 on 2024-04-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0004_portfolio_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='user',
            name='portfolios',
            field=models.ManyToManyField(to='portfolio_management.portfolio'),
        ),
    ]
