# Generated by Django 4.1 on 2024-04-19 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio_management', '0005_remove_user_portfolio_user_portfolios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='portfolios',
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.TextField(default='Basic'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='owners',
            field=models.ManyToManyField(related_name='holdings', to=settings.AUTH_USER_MODEL),
        ),
    ]
