# Generated by Django 4.1 on 2024-04-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0006_remove_user_portfolios_user_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='owners',
        ),
        migrations.AddField(
            model_name='user',
            name='holdings',
            field=models.ManyToManyField(related_name='owners', to='portfolio_management.portfolio'),
        ),
    ]
